### ISSUE TITLE
kivymd

### ISSUE THREAD

**Issue by dovahkinnn** [gottadiveintopython/kveditor#2]
support kivymd ?

**Comment by gottadiveintopython** [comment]
Yeah probably, I haven't tried yet, though.

**Comment by gottadiveintopython** [comment]
@dovahkinnn ?

**Comment by dovahkinnn** [comment]
ı cant try yet  ım using kaki

**Comment by gottadiveintopython** [comment]
OK, when you tried, if any problem occurred, re-open the PR.
